### PR TITLE
fix(cache): fixed cache timeout

### LINKED ISSUE #17: Scheduled cache purging based on LastPull attribute is not executed.
## Description

The switch case statement in cfclient/cfapps/cache.go that checks the LastPull time for each application in the cache to remove old entries does not get executed. Only UpdateInstances and adding new applications to the cache ever get executed.

This can cause: 
-  If an application in the cache no longer exists, the nozzle will continue to attempt to update instance details for that application and trigger HTTP 404 errors.
-  If the rate limiter causes the initial FetchApp calls to timeout, an app.name attribute can get stuck with the value of WAITING FOR DATA. Since FetchApp is only called for new applications and the cached applications are never removed, the WAITING FOR DATA app.name would never be updated.
- If VCAP details for an existing application to enable multi-account event router are updated (RPM account ID / Insights insert key) those changes would not take effect until the nozzle is restarted.

This behavior

## Steps to Reproduce

A logging statement can be added to the case statement for time.NewTicker(cacheDuration * time.Minute).C to show that the logic isn't executed.

## Expected Behavior

The scheduled cache purge should be corrected so that cached application data is only used for ~30 minutes and then FetchApp will be called to get updated application data when a ContainerMetric or LogMessage envelope type is received for that application GUID again.

### PR DESCRIPTION
**Pull request by paologallinaharbur**
The cache was not being cleaned on timeout, this was causing several issues, having old apps getting stuck

fix #17

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -85,7 +77,7 @@ func set() *Config {
 	// Rate limiter burst limit
 	v.SetDefault("FIREHOSE_RATE_BURST", 5)
 	// Rate limiter timeout in seconds.
-	v.SetDefault("FIREHOSE_RATE_TIMEOUT_SECS", 30)
+	v.SetDefault("FIREHOSE_RATE_TIMEOUT_SECS", 60)
```
Comment (gsanchezgavier) [inline config/config.go:80]: why is this increased?

**Review by gsanchezgavier — APPROVED** [review]
lgtm

File: config/config.go (hunk 1 above)
Comment (paologallinaharbur) [reply config/config.go:80]: discussed offline
